### ISSUE TITLE
Problem with config file

### ISSUE THREAD

**Issue by jeanq1** [milmillin/ReparamCAD#1]
Hi ! 
I've been trying to run this project after reading the paper, but I seem to be missing the hydra config file, do you think you can provide the general template for it ?
Thanks !
Jean

**Comment by milmillin** [comment]
Hi,

Here is the `conf/config.yaml` I forgot to include:
```yaml
hydra:
  run:
    dir: output/${name}/${task.name}--${init.model}--${prompt}
  job:
    chdir: true
defaults:
  - base_config
  - task: sd
  - _self_
 ```

This is just for changing the directories and setting some defaults. Also here is the full `config.yaml`:
```yaml
name: my-run-01
prompt: a pickup truck
task:
  name: sd
  ddim_steps: 50
  strength: 0.75
camera:
  fov_min: 40.0
  fov_max: 40.0
  dist_min: 2.0
  dist_max: 2.0
  elev_min: 5.0
  elev_max: 50.0
  azim_min: -180.0
  azim_max: 180.0
  aug_loc: false
  shift_max: 0.5
  overhead_thresh: 60.0
  front_thresh: 60.0
render:
  res: 512
  spp: 2
  bg_mode: white
  k_s: 0.04
  n_s: 50.0
opt:
  max_iter: 400
  cam_poses_per_iter: 5
  steps_per_iter: 30
  sd_per_pose: 3
  lr_base: 0.05
  lr_ramp: 1.0
  blur_kernel_size: 13
  blur_sigma: 2.0
  preprocess: laplace
  laplace_strength: 0.3
  reduce_diffused: like-org
  regularizer: 0.001
init:
  model: car
```

The important ones are: `name`: name of the output folder, `prompt`, and `init.model` which I usually set through CLI. Also see [config.py](https://github.com/milmillin/ReparamCAD/blob/main/rpcad/config.py) for a little more description of other configs.

Best,
Milin
